name: Check Version Consistency

on: [push, pull_request]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Check version consistency
      run: |
        import re
        import sys

        # Read library.properties
        with open('library.properties', 'r', encoding='utf-8') as f:
            properties_content = f.read()
        
        # Extract version from library.properties
        properties_version = re.search(r'^version=(.*)$', properties_content, re.MULTILINE).group(1)

        # Read library.json
        import json
        with open('library.json', 'r', encoding='utf-8') as f:
            json_content = json.load(f)
        
        # Extract version from library.json
        json_version = json_content['version']

        # Check if versions match
        if properties_version != json_version:
            print(f"::warning file=library.properties::Version mismatch: library.properties ({properties_version}) and library.json ({json_version})")
            sys.exit(1)
