name: Tag on version change

on:
  push:
    branches:
      - main  # 実行するブランチを指定

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get current version from library.json
        id: get_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' library.json)
          echo "Current version: $CURRENT_VERSION"
          echo "::set-output name=version::$CURRENT_VERSION"

      - name: Check if version has changed in the commit
        id: check_version_change
        run: |
          # Check if the version in the last commit has been modified
          if git diff --name-only HEAD^ HEAD | grep -q 'library.json'; then
            echo "library.json has been modified"
            
            # Get the version before the commit
            PREVIOUS_VERSION=$(git show HEAD^:library.json | jq -r '.version')
            echo "Previous version: $PREVIOUS_VERSION"
            
            if [ "$PREVIOUS_VERSION" != "${{ steps.get_version.outputs.version }}" ]; then
              echo "Version has changed from $PREVIOUS_VERSION to ${{ steps.get_version.outputs.version }}"
              echo "::set-output name=version_changed::true"
            else
              echo "Version has not changed."
              echo "::set-output name=version_changed::false"
            fi
          else
            echo "library.json was not modified."
            echo "::set-output name=version_changed::false"
          fi

      - name: Create tag
        if: steps.check_version_change.outputs.version_changed == 'true'
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo "Creating tag for version $VERSION"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v$VERSION" -m "Tag for version $VERSION"
          git push origin "v$VERSION"
