name: Convert Word files to Markdown

on:
  push:
    paths:
      - 'docs/*.docx'

permissions:
  contents: write  # リポジトリへの書き込み権限を付与

jobs:
  convert-docx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Create output directory and clean it
      run: |
        rm -rf output  # outputディレクトリを削除
        mkdir -p output  # 新しくoutputディレクトリを作成

    - name: List Word files in docs/
      run: ls docs/

    - name: Convert all Word files to Markdown
      run: |
        for file in docs/*.docx; do
          filename=$(basename "$file" .docx)  # ファイル名から拡張子を除去
          pandoc "$file" --extract-media=output/media -t markdown -o "output/$filename.md"  # 画像を含めて変換
        done

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKENを設定
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/*.md output/media/*
        git commit -m "Auto-converted Word files to Markdown with media"
        git push
