name: Convert Word files to Markdown

on:
  push:
    paths:
      - 'docs/*.docx'

jobs:
  convert-docx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Create output directory if it doesn't exist
      run: mkdir -p output  # outputディレクトリを作成

    - name: List Word files in docs/
      run: ls docs/

    - name: Convert all Word files to Markdown
      run: |
        for file in docs/*.docx; do
          filename=$(basename "$file" .docx)  # ファイル名から拡張子を除去
          pandoc "$file" -t markdown -o "output/$filename.md"  # Markdownに変換
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/*.md
        git commit -m "Auto-converted Word files to Markdown"
        git push
